# THIS IS ONLY FOR RUNNING INDIVIDUAL MONGO RUNNING
# IF YOU USE ROOT LEVEL COMPOSE THEN DONT USE IT

version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logsdb
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    external: true
